</main>
</div>
</div>

<script src="/js/jquery.min.js"></script>
<script src="/bootstrap/js/bootstrap.js"></script>
<script src="/clipboard/dist/clipboard.min.js"></script>
<script src="/js/karman.js?t=<?=time()?>"></script>

<!--<script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script><script src="dashboard.js"></script>-->
</body>
</html>
